services:
  php:
    container_name: setup-lp_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./site:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-lp_network
    depends_on:
      - mysql

  nginx:
    container_name: setup-lp_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./site:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-lp_network

  mysql:
    image: mysql:8.0
    container_name: setup-lp_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: setup_lp
      MYSQL_USER: setup
      MYSQL_PASSWORD: setup
    volumes:
      - ./db.sql:/db.sql
      - setup-data:/var/lib/mysql
    networks:
      - setup-lp_network

networks:
  setup-lp_network:
    driver: bridge

volumes:
  setup-data:
    driver: local
